services:
  kindle-dashboard:
    build: .
    ports:
      - "10876:8080" # Single server for both dashboard and battery updates
    environment:
      TZ: Asia/Manila
    volumes:
      - ./public:/app/public
    restart: always
